export const ADD = 'ADD'; 
export const REMOVE = 'REMOVE'; 
export const GET_INGREDIENTS = 'GET_INGREDIENTS';
export const HANDLE_ERROR = 'HANDLE_ERROR';
export const GO_BACK_TO_CHECKOUT = 'GO_BACK_TO_CHECKOUT';

export const PURCHASE_BURGER_INIT = 'PUECHASE_BURGER_INIT';
export const PURCHASE_BURGER_START = 'PUECHASE_BURGER_START';
export const PURCHASE_BURGER_SUCCESS = 'PURCHASE_BURGER_SUCCESS';
export const PURCHASE_BURGER_FAIL = 'PURCHASE_BURGER_FAIL';
export const GET_ORDERS = 'GET_ORDERS';

export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
